// <auto-generated />
namespace bilibili.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createdtabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdtabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191109304_createdtabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
